# Generated by Django 4.2.19 on 2025-02-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Contact',
        ),
    ]
