# Generated by Django 4.2.19 on 2025-02-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_person_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
